research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

post_newsletter_task:
  name: Post Newsletter to LinkedIn
  description: Transform and publish newsletter content to LinkedIn
  goal: Successfully publish newsletter content as an engaging LinkedIn post
  parameters:
    - name: newsletter_content
      type: string
      description: The finalized newsletter content to be posted
  steps:
    - name: format_content
      description: Format the newsletter content for LinkedIn
      validation:
        - ensure content length is within LinkedIn limits (3000 characters)
        - verify no sensitive information is included
        - check for appropriate formatting and line breaks
    - name: create_post
      description: Create and validate the LinkedIn post
      validation:
        - verify all links are valid
        - ensure hashtags are properly formatted
        - check for appropriate call-to-action
    - name: publish
      description: Publish the post to LinkedIn
      validation:
        - confirm successful post creation
        - verify post visibility settings
        - log post ID and timestamp
  output:
    - name: post_id
      type: string
      description: The ID of the published LinkedIn post
    - name: post_url
      type: string
      description: The URL of the published LinkedIn post
  error_handling:
    - on_failure: log error details and notify administrator
    - retry_count: 3
    - retry_delay: 60
